### ISSUE TITLE
Cuts first char

### ISSUE THREAD

**Issue by muellerlukas** [timcrockford/track-custom-keywords#2]
Hi,
I just realised in combination with some other plugins, the first char will be cutten in the database.
That problem exists only with the plugin "hypens in urls". I fixed it by replaing
    >yourls_add_filter( 'random_keyword', 'tck_add_random' );
    >yourls_add_filter( 'custom_keyword', 'tck_add_custom' );
with
    >yourls_add_filter( 'random_keyword', 'tck_add_random', 99 );
    >yourls_add_filter( 'custom_keyword', 'tck_add_custom', 99 );

**Comment by timcrockford** [comment]
Hi MuellerLukas! Sorry for the delay in the reply - you're quite right, other plugins that strip out the custom characters this plugin users will cause the behaviour you're describing, and decreasing the priority on the add functions resolve that. I've pushed a change to the master branch that implements the change, you should be able to pull it down and update it (although you've probably made the change manually already!)
